# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventory.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finventory.proto\x12\tinventory\"\xfa\x01\n\x0fInventoryRecord\x12\x14\n\x0cinventory_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x12\n\nunit_price\x18\x04 \x01(\x05\x12\x19\n\x11quantity_in_stock\x18\x05 \x01(\x05\x12\x17\n\x0finventory_value\x18\x06 \x01(\x05\x12\x15\n\rreorder_level\x18\x07 \x01(\x05\x12\x1c\n\x14reorder_time_in_days\x18\x08 \x01(\x05\x12\x1b\n\x13quantity_in_reorder\x18\t \x01(\x05\x12\x14\n\x0c\x64iscontinued\x18\n \x01(\t\"0\n\tSearchReq\x12\x10\n\x08key_name\x18\x01 \x01(\t\x12\x11\n\tkey_value\x18\x02 \x01(\t\"A\n\tSearchRes\x12\x34\n\x10inventory_record\x18\x01 \x01(\x0b\x32\x1a.inventory.InventoryRecord\"@\n\x08RangeRes\x12\x34\n\x10inventory_record\x18\x01 \x03(\x0b\x32\x1a.inventory.InventoryRecord\"@\n\x08RangeReq\x12\x10\n\x08key_name\x18\x01 \x01(\t\x12\x11\n\tkey_start\x18\x02 \x01(\x05\x12\x0f\n\x07key_end\x18\x03 \x01(\x05\"?\n\x07\x44istRes\x12\x34\n\x10inventory_record\x18\x01 \x03(\x0b\x32\x1a.inventory.InventoryRecord\"/\n\x07\x44istReq\x12\x10\n\x08key_name\x18\x01 \x01(\t\x12\x12\n\npercentile\x18\x02 \x01(\x01\"Y\n\tUpdateReq\x12\x10\n\x08key_name\x18\x01 \x01(\t\x12\x11\n\tkey_value\x18\x02 \x01(\t\x12\x10\n\x08val_name\x18\x03 \x01(\t\x12\x15\n\rval_value_new\x18\x04 \x01(\t2\xb7\x02\n\tInventory\x12\x44\n\nSearchByID\x12\x1a.inventory.InventoryRecord\x1a\x1a.inventory.InventoryRecord\x12\x34\n\x06Search\x12\x14.inventory.SearchReq\x1a\x14.inventory.SearchRes\x12\x37\n\x0bSearchRange\x12\x13.inventory.RangeReq\x1a\x13.inventory.RangeRes\x12\x39\n\x0fGetDistribution\x12\x12.inventory.DistReq\x1a\x12.inventory.DistRes\x12:\n\x06Update\x12\x14.inventory.UpdateReq\x1a\x1a.inventory.InventoryRecordb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INVENTORYRECORD']._serialized_start=31
  _globals['_INVENTORYRECORD']._serialized_end=281
  _globals['_SEARCHREQ']._serialized_start=283
  _globals['_SEARCHREQ']._serialized_end=331
  _globals['_SEARCHRES']._serialized_start=333
  _globals['_SEARCHRES']._serialized_end=398
  _globals['_RANGERES']._serialized_start=400
  _globals['_RANGERES']._serialized_end=464
  _globals['_RANGEREQ']._serialized_start=466
  _globals['_RANGEREQ']._serialized_end=530
  _globals['_DISTRES']._serialized_start=532
  _globals['_DISTRES']._serialized_end=595
  _globals['_DISTREQ']._serialized_start=597
  _globals['_DISTREQ']._serialized_end=644
  _globals['_UPDATEREQ']._serialized_start=646
  _globals['_UPDATEREQ']._serialized_end=735
  _globals['_INVENTORY']._serialized_start=738
  _globals['_INVENTORY']._serialized_end=1049
# @@protoc_insertion_point(module_scope)
